import mongoose from 'mongoose';

const alertSchema = new mongoose.Schema({
  type: {
    type: String,
    enum: [
      'STOCK_LOW', 'STOCK_OUT', 'EXPIRY_WARNING', 'BATCH_EXPIRED',
      'SHIPMENT_DELAYED', 'QUALITY_ISSUE', 'ANOMALY_DETECTED',
      'SUPPLIER_PERFORMANCE', 'CYCLE_COUNT_DISCREPANCY',
      'FORECAST_DEVIATION', 'WEATHER_IMPACT', 'SYSTEM_ERROR'
    ],
    required: true
  },
  severity: {
    type: String,
    enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'],
    default: 'MEDIUM'
  },
  title: { type: String, required: true },
  message: { type: String, required: true },
  description: String,
  relatedEntities: {
    product: { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
    batch: { type: mongoose.Schema.Types.ObjectId, ref: 'Batch' },
    shipment: { type: mongoose.Schema.Types.ObjectId, ref: 'Shipment' },
    supplier: { type: mongoose.Schema.Types.ObjectId, ref: 'Supplier' },
    order: { type: mongoose.Schema.Types.ObjectId, ref: 'Order' },
    warehouse: { type: mongoose.Schema.Types.ObjectId, ref: 'Warehouse' },
    cycleCount: { type: mongoose.Schema.Types.ObjectId, ref: 'CycleCount' }
  },
  metrics: {
    currentValue: Number,
    thresholdValue: Number,
    deviation: Number,
    percentageChange: Number
  },
  status: {
    type: String,
    enum: ['ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', 'FALSE_POSITIVE'],
    default: 'ACTIVE'
  },
  actions: [{
    action: {
      type: String,
      enum: ['REORDER', 'INSPECT', 'QUARANTINE', 'NOTIFY_SUPPLIER', 'ADJUST_FORECAST', 'REVIEW_PROCESS']
    },
    description: String,
    assignedTo: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    dueDate: Date,
    completed: { type: Boolean, default: false },
    completedAt: Date,
    completedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }
  }],
  autoGenerated: { type: Boolean, default: true },
  recurring: {
    isRecurring: { type: Boolean, default: false },
    frequency: String, // cron expression or simple interval
    nextOccurrence: Date
  },
  notifications: {
    emailSent: { type: Boolean, default: false },
    emailSentAt: Date,
    smsSent: { type: Boolean, default: false },
    smsSentAt: Date,
    pushSent: { type: Boolean, default: false },
    pushSentAt: Date
  },
  acknowledgedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  acknowledgedAt: Date,
  resolvedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  resolvedAt: Date,
  resolution: String,
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }
}, {
  timestamps: true
});

// Indexes
alertSchema.index({ type: 1, status: 1 });
alertSchema.index({ severity: 1 });
alertSchema.index({ status: 1 });
alertSchema.index({ 'relatedEntities.product': 1 });
alertSchema.index({ 'relatedEntities.shipment': 1 });
alertSchema.index({ createdAt: -1 });
alertSchema.index({ 'recurring.nextOccurrence': 1 });

// Virtual for isOverdue
alertSchema.virtual('isOverdue').get(function() {
  if (!this.actions || this.actions.length === 0) return false;
  return this.actions.some(action =>
    !action.completed &&
    action.dueDate &&
    action.dueDate < new Date()
  );
});

const Alert = mongoose.model('Alert', alertSchema);
export default Alert;